export const locations = [
  {
    id: 1,
    name: "Citadel",
    type: "Space Station",
    system: "Serpent Nebula",
    classification: "Galactic Capital",
    population: "13.2 million",
    description:
      "The political and cultural heart of galactic civilization, serving as the seat of the Citadel Council.",
    significance: "Galactic Government",
    status: "Active",
    controlledBy: "Citadel Council",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 2,
    name: "Earth",
    type: "Planet",
    system: "Sol System",
    classification: "Human Homeworld",
    population: "11.4 billion",
    description:
      "The birthplace of humanity and capital of the Systems Alliance.",
    significance: "Human Capital",
    status: "Recovering",
    controlledBy: "Systems Alliance",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 3,
    name: "Thessia",
    type: "Planet",
    system: "Parnitha System",
    classification: "Asari Homeworld",
    population: "5.5 billion",
    description:
      "The ancient homeworld of the Asari, known for its advanced civilization and Prothean ruins.",
    significance: "Asari Capital",
    status: "Damaged",
    controlledBy: "Asari Republics",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 4,
    name: "Palaven",
    type: "Planet",
    system: "Trebia System",
    classification: "Turian Homeworld",
    population: "6.1 billion",
    description:
      "The militaristic homeworld of the Turians, featuring massive fortress-cities and military academies.",
    significance: "Turian Capital",
    status: "Fortified",
    controlledBy: "Turian Hierarchy",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 5,
    name: "Sur'Kesh",
    type: "Planet",
    system: "Annos Basin",
    classification: "Salarian Homeworld",
    population: "10.3 billion",
    description:
      "The high-gravity homeworld of the Salarians, featuring advanced research facilities and cities.",
    significance: "Salarian Capital",
    status: "Active",
    controlledBy: "Salarian Union",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 6,
    name: "Omega",
    type: "Space Station",
    system: "Sahrabarik System",
    classification: "Criminal Haven",
    population: "7.8 million",
    description:
      "A lawless asteroid mining station that serves as a hub for mercenaries, criminals, and refugees.",
    significance: "Criminal Hub",
    status: "Chaotic",
    controlledBy: "Aria T'Loak",
    image: "/placeholder.svg?height=200&width=300",
  },
];
