export const locations = [
  {
    name: "The Citadel",
    type: "Space Station",
    system: "Widow System",
    status: "Active",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "The massive space station serves as the capital of the Citadel Council and the hub of galactic civilization.",
    features: ["Council Chambers", "Presidium", "Wards", "C-Sec Academy"],
    population: "13.2 million",
    security: "C-Sec",
    significance: "Political, Economic, Cultural Center",
  },
  {
    name: "Thessia",
    type: "Homeworld",
    system: "Parnitha",
    status: "Inhabited",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "Homeworld of the asari and the most advanced civilization in the known galaxy.",
    features: [
      "Ancient Temples",
      "Research Centers",
      "Biotic Academies",
      "Crystal Spires",
    ],
    population: "5.5 billion",
    security: "Asari Military",
    significance: "Asari Homeworld, Cultural Center",
  },
  {
    name: "Palaven",
    type: "Homeworld",
    system: "Trebia",
    status: "Inhabited",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "Homeworld of the turians, known for its strong military presence and strategic importance.",
    features: [
      "Military Bases",
      "Defense Grid",
      "Training Facilities",
      "Government Centers",
    ],
    population: "6.1 billion",
    security: "Turian Military",
    significance: "Turian Homeworld, Military Hub",
  },
  {
    name: "Sur'Kesh",
    type: "Homeworld",
    system: "Pranas",
    status: "Inhabited",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "Homeworld of the salarians, characterized by its advanced research facilities and technological developments.",
    features: [
      "Research Labs",
      "Tech Centers",
      "STG Facilities",
      "Universities",
    ],
    population: "3.2 billion",
    security: "Salarian Union",
    significance: "Salarian Homeworld, Research Hub",
  },
  {
    name: "Tuchanka",
    type: "Homeworld",
    system: "Aralakh",
    status: "Inhabited",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "The irradiated and hostile homeworld of the krogan, bearing the scars of nuclear war.",
    features: [
      "Ancient Ruins",
      "Clan Grounds",
      "Sacred Sites",
      "Radiation Zones",
    ],
    population: "2.1 billion",
    security: "Clan Forces",
    significance: "Krogan Homeworld, Historical Site",
  },
  {
    name: "Omega",
    type: "Space Station",
    system: "Sahrabarik",
    status: "Active",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "A lawless space station in the Terminus Systems, known as a haven for criminals and mercenaries.",
    features: ["Afterlife Club", "Slums", "Markets", "Mining Operations"],
    population: "7.8 million",
    security: "Mercenary Groups",
    significance: "Criminal Hub, Strategic Location",
  },
  {
    name: "Illium",
    type: "Colony World",
    system: "Tasale",
    status: "Inhabited",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "A corporate world known for its luxury, trading, and legally questionable business practices.",
    features: [
      "Trading Floor",
      "Corporate Towers",
      "Luxury Districts",
      "Spaceports",
    ],
    population: "85 million",
    security: "Corporate Security",
    significance: "Trade Hub, Corporate Center",
  },
  {
    name: "Rannoch",
    type: "Homeworld",
    system: "Tikkun",
    status: "Disputed",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "The quarian homeworld, contested between its original inhabitants and the geth.",
    features: [
      "Ancient Cities",
      "Geth Structures",
      "Arid Landscapes",
      "Clean Environment",
    ],
    population: "Disputed",
    security: "Geth/Quarian Forces",
    significance: "Quarian Homeworld, Geth Hub",
  },
  {
    name: "Noveria",
    type: "Corporate World",
    system: "Pax",
    status: "Restricted Access",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "A corporate world known for its controversial private research labs and extreme weather conditions.",
    features: ["Research Labs", "Corporate Offices", "Port Hanshan", "Peak 15"],
    population: "400,000",
    security: "ERCS",
    significance: "Research Hub, Corporate Haven",
  },
  {
    name: "Feros",
    type: "Colony World",
    system: "Theseus",
    status: "Recovering",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "A human colony built on ancient Prothean ruins, known for its massive skyscrapers and historical significance.",
    features: ["Prothean Ruins", "ExoGeni Facility", "Skyway", "Zhu's Hope"],
    population: "300,000",
    security: "Colonial Militia",
    significance: "Archaeological Site, Human Colony",
  },
  {
    name: "Eden Prime",
    type: "Colony World",
    system: "Utopia",
    status: "Recovering",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "A pristine human colony world and agricultural center, site of the first Reaper attack on humanity.",
    features: [
      "Agricultural Centers",
      "Research Outposts",
      "Prothean Ruins",
      "Defense Towers",
    ],
    population: "3.7 million",
    security: "Alliance Military",
    significance: "Human Colony, Historical Site",
  },
  {
    name: "Bekenstein",
    type: "Colony World",
    system: "Boltzmann",
    status: "Affluent",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "Known as the 'human Illium,' Bekenstein is a wealthy human colony and cultural center.",
    features: [
      "Luxury Districts",
      "Financial Centers",
      "Entertainment Venues",
      "Mansions",
    ],
    population: "5.4 million",
    security: "Private Security",
    significance: "Economic Hub, Cultural Center",
  },
  {
    name: "Kahje",
    type: "Homeworld",
    system: "Zaherin",
    status: "Inhabited",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "The ocean world home to both the hanar and the drell, known for its vast underwater cities.",
    features: [
      "Underwater Cities",
      "Surface Domes",
      "Prothean Ruins",
      "Environmental Shields",
    ],
    population: "1.8 billion",
    security: "Illuminated Primacy",
    significance: "Hanar Homeworld, Drell Refuge",
  },
];
