export const militaryForces = [
  {
    name: "Systems Alliance Navy",
    type: "Human Military",
    headquarters: "Arcturus Station",
    status: "Active",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "The military and exploratory spearhead of human civilization, the Systems Alliance is responsible for the defense and expansion of Earth's interests.",
    strengths: [
      "Advanced Technology",
      "Rapid Adaptation",
      "Strong Leadership",
      "Diverse Tactics",
    ],
    specialization: "Combined Arms Operations",
    notableUnits: ["N7 Special Forces", "SSV Normandy", "2nd Fleet"],
    commandStructure: "Alliance Parliament",
  },
  {
    name: "Turian Hierarchy",
    type: "Turian Military",
    headquarters: "Palaven",
    status: "Active",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "The largest and most powerful military force in Citadel space, known for their strict discipline and effectiveness.",
    strengths: [
      "Superior Discipline",
      "Advanced Fleet",
      "Strategic Excellence",
      "Large Numbers",
    ],
    specialization: "Fleet Operations",
    notableUnits: ["Blackwatch", "15th Striker Legion", "43rd Marine Division"],
    commandStructure: "Primarch Command",
  },
  {
    name: "Asari Commandos",
    type: "Special Forces",
    headquarters: "Thessia",
    status: "Active",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "Elite special forces units composed of ancient and powerful asari warriors, renowned for their biotic abilities and tactical prowess.",
    strengths: [
      "Biotic Mastery",
      "Centuries of Experience",
      "Stealth Operations",
      "Advanced Technology",
    ],
    specialization: "Covert Operations",
    notableUnits: [
      "Serrice Guard",
      "Destiny Ascension Crew",
      "Thessian Temple Guard",
    ],
    commandStructure: "Asari High Command",
  },
  {
    name: "Salarian STG",
    type: "Intelligence Service",
    headquarters: "Sur'Kesh",
    status: "Active",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "The Special Tasks Group handles espionage, intelligence gathering, and covert operations for the Salarian Union.",
    strengths: [
      "Intelligence Gathering",
      "Advanced Tech",
      "Stealth",
      "Rapid Deployment",
    ],
    specialization: "Espionage",
    notableUnits: ["Aegohr Team", "Veshok Squad", "Special Recon"],
    commandStructure: "STG Command",
  },
  {
    name: "Krogan Mercenaries",
    type: "Independent Forces",
    headquarters: "Tuchanka",
    status: "Active",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "Following the Krogan Rebellions, many krogan have found work as mercenaries, valued for their combat prowess and durability.",
    strengths: [
      "Physical Power",
      "Combat Experience",
      "Regeneration",
      "Shock Tactics",
    ],
    specialization: "Heavy Infantry",
    notableUnits: ["Aralakh Company", "Blood Pack", "Urdnot Clan Warriors"],
    commandStructure: "Various Clan Leaders",
  },
  {
    name: "Quarian Migrant Fleet",
    type: "Naval Force",
    headquarters: "Migrant Fleet",
    status: "Active",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "The largest fleet in the galaxy, though primarily focused on protecting and sustaining the quarian population.",
    strengths: [
      "Technical Expertise",
      "Adaptability",
      "Fleet Coordination",
      "Resource Efficiency",
    ],
    specialization: "Fleet Operations",
    notableUnits: ["Heavy Fleet", "Patrol Fleet", "Special Projects"],
    commandStructure: "Admiralty Board",
  },
  {
    name: "Geth Collective",
    type: "Synthetic Army",
    headquarters: "Perseus Veil",
    status: "Active",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "A collective of networked AI platforms capable of rapid deployment and adaptation to battlefield conditions.",
    strengths: [
      "Networked Intelligence",
      "Rapid Manufacturing",
      "Expendable Units",
      "Advanced Technology",
    ],
    specialization: "Synthetic Warfare",
    notableUnits: ["Prime Units", "Hunter Platforms", "Colossus Units"],
    commandStructure: "Geth Consensus",
  },
  {
    name: "Spectres",
    type: "Special Agents",
    headquarters: "Citadel",
    status: "Active",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "Elite agents entrusted with the authority to preserve galactic stability by any means necessary.",
    strengths: [
      "Autonomy",
      "Best Equipment",
      "Diverse Skills",
      "Legal Immunity",
    ],
    specialization: "Special Operations",
    notableUnits: ["Individual Agents"],
    commandStructure: "Citadel Council",
  },
  {
    name: "Eclipse",
    type: "Mercenary Organization",
    headquarters: "Omega",
    status: "Active",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "A mercenary corporation known for its tech expertise and biotic capabilities, founded by an asari commando.",
    strengths: [
      "Tech Expertise",
      "Biotic Support",
      "Corporate Structure",
      "Advanced Equipment",
    ],
    specialization: "Tech Warfare",
    notableUnits: ["Eclipse Sisters", "Eclipse Engineers", "Heavy Mechs"],
    commandStructure: "Corporate Hierarchy",
  },
  {
    name: "Blue Suns",
    type: "Mercenary Organization",
    headquarters: "Omega",
    status: "Active",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "A private security organization that evolved into a powerful mercenary group, operating throughout the Terminus Systems.",
    strengths: [
      "Professional Training",
      "Heavy Weapons",
      "Varied Species",
      "Large Numbers",
    ],
    specialization: "Security Operations",
    notableUnits: ["Blue Suns Command", "Shock Troopers", "Heavy Infantry"],
    commandStructure: "Military Hierarchy",
  },
  {
    name: "Blood Pack",
    type: "Mercenary Organization",
    headquarters: "Omega",
    status: "Active",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "A mercenary group known for its brutality, composed primarily of krogan and vorcha.",
    strengths: ["Brute Force", "Regeneration", "Fear Tactics", "Adaptability"],
    specialization: "Shock Troops",
    notableUnits: [
      "Krogan Warlords",
      "Vorcha Shock Troops",
      "Blood Pack Pyros",
    ],
    commandStructure: "Krogan Leadership",
  },
  {
    name: "C-Sec",
    type: "Law Enforcement",
    headquarters: "Citadel",
    status: "Active",
    image: "/placeholder.svg?height=400&width=600",
    description:
      "The Citadel Security Services, responsible for maintaining law and order on the Citadel.",
    strengths: ["Training", "Authority", "Equipment", "Information Network"],
    specialization: "Law Enforcement",
    notableUnits: ["Investigation Division", "Customs", "Special Response"],
    commandStructure: "Executor Command",
  },
];
